spring.application.name=loan-application-evaluator
server.port=8084

spring.datasource.url=jdbc:h2:mem:loanauditdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console for development
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.com.lending=DEBUG